export const FETCH_AUTH_ADDRESS_SUCCESS= "FETCH_AUTH_ADDRESS_SUCCESS";
export const FETCH_AUTH_ADDRESS_ERROR = "FETCH_AUTH_ADDRESS_EEROR";
export const ADDRESS_STATE = "ADDRESS_STATE";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_ERROR = "CREATE_ADDRESS_ERROR";
